using System.Linq;
using System.Text;
using PLang.Generators.Discovery;
using PLang.Generators.Emission.Property;
using ProviderProperty = PLang.Generators.Emission.Property.Provider.@this;

namespace PLang.Generators.Emission.Action;

/// <summary>
/// Per-handler emission. Builds the partial-class shell, marker auto-provisions,
/// per-property bodies (delegated to ActionProperty.EmitProperty), the thin
/// ExecuteAsync, and the __SnapshotParams body (delegated to
/// ActionProperty.EmitSnapshotEntry).
/// </summary>
public static class @this
{
    public static string Emit(ActionClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text.RegularExpressions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"partial class {info.ClassName} : global::App.modules.ICodeGenerated");
        sb.AppendLine("{");

        EmitMarkers(sb, info);
        EmitResolutionState(sb);
        EmitProperties(sb, info);
        EmitDataAndErrorHelpers(sb, info);
        EmitExecuteAsync(sb, info);
        EmitSnapshotPublic(sb);
        EmitLegacyHelpers(sb);
        EmitSnapshotInternal(sb, info);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMarkers(StringBuilder sb, ActionClassInfo info)
    {
        if (info.ImplementsIContext)
        {
            sb.AppendLine("    public global::App.Actor.Context.@this Context { get; set; } = null!;");
            sb.AppendLine();
        }
        if (info.ImplementsIChannel)
        {
            sb.AppendLine("    public global::App.Channels.@this Channels { get; set; } = null!;");
            sb.AppendLine();
        }
        if (info.ImplementsIAction)
        {
            sb.AppendLine("    public global::App.Goals.Goal.Steps.Step.Actions.Action.@this Action { get; set; } = null!;");
            sb.AppendLine();
        }
        if (info.ImplementsIStep)
        {
            sb.AppendLine("    public global::App.Goals.Goal.Steps.Step.@this Step { get; set; } = null!;");
            sb.AppendLine();
        }
        if (info.ImplementsIStatic)
        {
            sb.AppendLine("    public System.Collections.Concurrent.ConcurrentDictionary<string, object?> Static { get; set; } = null!;");
            sb.AppendLine();
        }
    }

    private static void EmitResolutionState(StringBuilder sb)
    {
        sb.AppendLine("    private global::App.Goals.Goal.Steps.Step.Actions.Action.@this? __action;");
        sb.AppendLine("    private global::App.@this? __app;");
        sb.AppendLine("    private global::App.Data.@this? __resolutionError;");
        sb.AppendLine();
    }

    private static void EmitProperties(StringBuilder sb, ActionClassInfo info)
    {
        foreach (var prop in info.Properties)
            prop.EmitProperty(sb);
    }

    private static void EmitDataAndErrorHelpers(StringBuilder sb, ActionClassInfo info)
    {
        var hasDataProp = info.Properties.Any(p => p.Name == "Data");
        if (!hasDataProp)
        {
            sb.AppendLine("    protected static global::App.Data.@this Data() => global::App.Data.@this.Ok();");
            sb.AppendLine("    protected static global::App.Data.@this Data(object? value) => global::App.Data.@this.Ok(value);");
            sb.AppendLine("    protected static global::App.Data.@this Data(object? value, global::App.Data.Type? type) => global::App.Data.@this.Ok(value, type);");
        }
        var hasErrorProp = info.Properties.Any(p => p.Name == "Error");
        if (!hasErrorProp)
        {
            sb.AppendLine("    protected static global::App.Data.@this Error(global::App.Errors.IError error) => global::App.Data.@this.FromError(error);");
        }
        sb.AppendLine();
    }

    private static void EmitExecuteAsync(StringBuilder sb, ActionClassInfo info)
    {
        sb.AppendLine("    public async System.Threading.Tasks.Task<global::App.Data.@this> ExecuteAsync(");
        sb.AppendLine("        global::App.Goals.Goal.Steps.Step.Actions.Action.@this action, global::App.Actor.Context.@this context)");
        sb.AppendLine("    {");
        sb.AppendLine("        __action = action;");
        sb.AppendLine("        __app = context.App;");
        sb.AppendLine("        var app = __app!;");
        sb.AppendLine("        __resolutionError = null;");

        // Reset backing fields per call (so reused handler instances re-derive).
        // Skip when action is null (direct C# composition via init — keep init values).
        sb.AppendLine("        if (action != null)");
        sb.AppendLine("        {");
        foreach (var prop in info.Properties)
        {
            if (prop is ProviderProperty) continue;
            sb.AppendLine($"            __{prop.Name}_backing = default;");
            sb.AppendLine($"            __{prop.Name}_set = false;");
        }
        sb.AppendLine("        }");
        sb.AppendLine("        var __step = __action?.Step;");
        sb.AppendLine("        var __callFrames = context.CallStack?.GetFrames() ?? (System.Collections.Generic.IReadOnlyList<global::App.CallStack.CallFrame>)System.Array.Empty<global::App.CallStack.CallFrame>();");

        if (info.ImplementsIContext) sb.AppendLine("        Context = context;");
        if (info.ImplementsIChannel) sb.AppendLine("        Channels = (context.Actor ?? app.User).Channels;");
        if (info.ImplementsIAction) sb.AppendLine("        Action = __action!;");
        if (info.ImplementsIStep) sb.AppendLine("        Step = __action?.Step!;");
        if (info.ImplementsIStatic)
        {
            var moduleNs = info.Namespace;
            const string prefix = "App.modules.";
            var moduleName = moduleNs.StartsWith(prefix)
                ? moduleNs.Substring(prefix.Length).Split('.')[0]
                : moduleNs;
            sb.AppendLine($"        Static = context.GetModuleStatic(\"{moduleName}\");");
        }

        // Eager [Provider] resolution
        foreach (var prop in info.Properties.OfType<ProviderProperty>())
        {
            sb.AppendLine($"        var __{prop.Name}_result = app.Providers.Get<{prop.TypeName}>();");
            sb.AppendLine($"        if (!__{prop.Name}_result.Success) return __{prop.Name}_result;");
            sb.AppendLine($"        __{prop.Name}_backing = __{prop.Name}_result.Value!;");
        }
        sb.AppendLine();

        // IEvent surface
        foreach (var name in info.IEventPropertyNames)
        {
            sb.AppendLine($"        if ({name}?.Event != null)");
            sb.AppendLine($"            context.Event = {name}.Event;");
        }

        // Legacy raw-scalar non-null validation (Phase 5 deletes these along with the legacy properties).
        foreach (var v in info.RawScalarValidations)
        {
            var lower = v.PropertyName.ToLowerInvariant();
            sb.AppendLine($"        if ({(v.IsString ? $"string.IsNullOrEmpty({v.PropertyName})" : $"{v.PropertyName} == null")})");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (__resolutionError != null) return __resolutionError;");
            sb.AppendLine($"            var __prValue = __action?.Parameters?.FirstOrDefault(p => string.Equals(p.Name, \"{v.PropertyName}\", System.StringComparison.OrdinalIgnoreCase))?.Value?.ToString() ?? \"(unknown)\";");
            sb.AppendLine($"            var __stepText = __step?.Text ?? \"(unknown step)\";");
            sb.AppendLine($"            if (__stepText.Length > 80) __stepText = __stepText[..80] + \"...\";");
            sb.AppendLine($"            var __err = new global::App.Errors.ServiceError(");
            sb.AppendLine($"                $\"'{{__prValue}}' is empty — nothing to use as '{lower}' in step: {{__stepText}}\", __step, __callFrames, \"MissingParameter\", 400);");
            sb.AppendLine($"            __err.Context = context;");
            sb.AppendLine($"            return global::App.Data.@this.FromError(__err);");
            sb.AppendLine("        }");
        }

        // [IsNotNull] validation
        if (info.HasAnyIsNotNull)
        {
            sb.AppendLine("        if (__action?.Parameters != null)");
            sb.AppendLine("        {");
            foreach (var name in info.IsNotNullProperties)
            {
                var lower = name.ToLowerInvariant();
                sb.AppendLine($"            if (__action?.Parameters.FirstOrDefault(d => string.Equals(d.Name, \"{lower}\", StringComparison.OrdinalIgnoreCase))?.Value == null)");
                sb.AppendLine($"                return global::App.Data.@this.FromError(new global::App.Errors.ServiceError(");
                sb.AppendLine($"                    \"'{lower}' must have a value\", __step, __callFrames, \"ValueRequired\", 400));");
            }
            sb.AppendLine("        }");
        }

        sb.AppendLine("        if (__resolutionError != null) return __resolutionError;");
        sb.AppendLine();
        sb.AppendLine("        return await Run();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitSnapshotPublic(StringBuilder sb)
    {
        // Public surface for App.Run's catch path.
        sb.AppendLine("    public System.Collections.Generic.List<global::App.Errors.ParamSnapshot> SnapshotParams()");
        sb.AppendLine("        => __SnapshotParams();");
        sb.AppendLine();
    }

    private static void EmitLegacyHelpers(StringBuilder sb)
    {
        // __Resolve<T> — used by LegacyScalarProperty emission. Phase 5 removes it.
        sb.AppendLine("    private T? __Resolve<T>(string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        var data = __action?.Parameters?.FirstOrDefault(");
        sb.AppendLine("            d => string.Equals(d.Name, name, StringComparison.OrdinalIgnoreCase));");
        sb.AppendLine("        data ??= __action?.Defaults?.FirstOrDefault(");
        sb.AppendLine("            d => string.Equals(d.Name, name, StringComparison.OrdinalIgnoreCase));");
        sb.AppendLine("        if (data == null) return default;");
        sb.AppendLine("        var typed = data.As<T>(Context);");
        sb.AppendLine("        if (!typed.Success) { __resolutionError = typed; return default; }");
        sb.AppendLine("        var __value = typed.Value;");
        sb.AppendLine("        if (__value is global::App.Goals.Goal.GoalCall __gc && __gc.Action == null)");
        sb.AppendLine("            __gc.Action = __action;");
        sb.AppendLine("        return __value;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // __ResolveData — used by DataProperty emission. Returns the raw Parameter Data; the property's
        // .As<T>(Context) does the walk.
        sb.AppendLine("    private global::App.Data.@this __ResolveData(string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        var data = __action?.GetParameter(name, Context!);");
        sb.AppendLine("        if (data == null) return global::App.Data.@this.NotFound(name);");
        sb.AppendLine("        data.Context = Context;");
        sb.AppendLine("        return data;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // __HasParam used by LegacyScalarProperty for value-type-with-default path.
        sb.AppendLine("    private bool __HasParam(string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        return (__action?.Parameters?.Any(d => string.Equals(d.Name, name, StringComparison.OrdinalIgnoreCase)) ?? false)");
        sb.AppendLine("            || (__action?.Defaults?.Any(d => string.Equals(d.Name, name, StringComparison.OrdinalIgnoreCase)) ?? false);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // __StripPercent used by [VariableName] string properties (legacy). Phase 5 removes.
        sb.AppendLine("    private string? __StripPercent(string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        var data = __action?.Parameters?.FirstOrDefault(");
        sb.AppendLine("            d => string.Equals(d.Name, name, StringComparison.OrdinalIgnoreCase));");
        sb.AppendLine("        data ??= __action?.Defaults?.FirstOrDefault(");
        sb.AppendLine("            d => string.Equals(d.Name, name, StringComparison.OrdinalIgnoreCase));");
        sb.AppendLine("        if (data?.Value is string str) return str.Trim('%');");
        sb.AppendLine("        return data?.Value?.ToString();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitSnapshotInternal(StringBuilder sb, ActionClassInfo info)
    {
        sb.AppendLine("    private System.Collections.Generic.List<global::App.Errors.ParamSnapshot> __SnapshotParams()");
        sb.AppendLine("    {");
        sb.AppendLine("        var __list = new System.Collections.Generic.List<global::App.Errors.ParamSnapshot>();");
        foreach (var prop in info.Properties)
            prop.EmitSnapshotEntry(sb);
        sb.AppendLine("        return __list;");
        sb.AppendLine("    }");
    }
}
