using System.Linq;
using System.Text;
using PLang.Generators.Discovery;
using PLang.Generators.Emission.Property;
using DataProperty = PLang.Generators.Emission.Property.Data.@this;
using CodeProperty = PLang.Generators.Emission.Property.Code.@this;

namespace PLang.Generators.Emission.Action;

/// <summary>
/// Per-handler emission. A handler instance is the per-execution home, built fresh
/// for every action run:
///   Resolve(action, context) — validates, decodes each .pr parameter into a local,
///     constructs a fresh instance via the object initializer (init auto-props), then
///     Attach()es runtime markers. Returns the ready handler (or a resolution error).
///   Attach(action, context)  — sets Context / Action / Step / Static / Channel / [Code]
///     provider / IEvent on THIS instance. Called by Resolve, and directly on prebound
///     (inline C#-composed) handlers whose params are already set.
///   Execute()                — runs the handler's typed Run(), wrapping bare exceptions
///     with the action's module.action context.
///
/// Emission uses C# raw string literals (`$$"""..."""`). With `$$`, single `{` `}`
/// are literal and `{{name}}` is interpolation.
/// </summary>
public static class @this
{
    public static string Emit(ActionClassInfo info)
    {
        var sb = new StringBuilder();

        sb.Append($$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Linq;
            using System.Text.RegularExpressions;

            namespace {{info.Namespace}};

            partial class {{info.ClassName}}(global::app.actor.context.@this __ctx) : global::app.module.ICodeGenerated, global::app.module.IClass
            {

            """);

        EmitMarkers(sb, info);
        EmitInstanceState(sb);
        EmitProperties(sb, info);
        EmitDataAndErrorHelpers(sb, info);
        EmitResolve(sb, info);
        EmitAttach(sb, info);
        EmitExecute(sb);
        EmitHelpers(sb);
        EmitSnapshotPublic(sb);
        EmitSnapshotInternal(sb, info);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMarkers(StringBuilder sb, ActionClassInfo info)
    {
        // Context is universal — every action runs inside one, and any value the handler
        // produces borns with it (Data() -> Context.Ok). Emitted unconditionally.
        sb.Append("""
                public global::app.actor.context.@this Context { get; set; } = __ctx;

            """);
        if (info.ImplementsIChannel)
            sb.Append("""
                    public global::app.channel.@this Channel { get; set; } = null!;

                """);
        if (info.ImplementsIAction)
            sb.Append("""
                    public global::app.goal.steps.step.actions.action.@this Action { get; set; } = null!;

                """);
        if (info.ImplementsIStep)
            sb.Append("""
                    public global::app.goal.steps.step.@this Step { get; set; } = null!;

                """);
        if (info.ImplementsIStatic)
            sb.Append("""
                    public System.Collections.Concurrent.ConcurrentDictionary<string, object?> Static { get; set; } = null!;

                """);
    }

    private static void EmitInstanceState(StringBuilder sb)
    {
        // The action is held only so __SnapshotParams can read the .pr-side values on
        // the failure path. Set in Attach.
        sb.Append("""
                private global::app.goal.steps.step.actions.action.@this? __action;

            """);
    }

    private static void EmitProperties(StringBuilder sb, ActionClassInfo info)
    {
        foreach (var prop in info.Properties)
            prop.EmitProperty(sb);
    }

    private static void EmitDataAndErrorHelpers(StringBuilder sb, ActionClassInfo info)
    {
        // A handler that produces a value borns it with its own Context (context-never-null).
        var hasDataProp = info.Properties.Any(p => p.Name == "Data");
        if (!hasDataProp)
        {
            sb.Append("""
                    protected global::app.data.@this Data() => Context.Ok();
                    protected global::app.data.@this Data(object? value) => Context.Ok(value);
                    protected global::app.data.@this Data(object? value, global::app.type.@this? type) => Context.Ok(value, type);

                """);
        }
        var hasErrorProp = info.Properties.Any(p => p.Name == "Error");
        if (!hasErrorProp)
        {
            sb.Append("""
                    protected static global::app.data.@this Error(global::app.error.IError error) => global::app.data.@this.FromError(error);

                """);
        }
        sb.AppendLine();
    }

    private static void EmitResolve(StringBuilder sb, ActionClassInfo info)
    {
        sb.Append("""
                public async System.Threading.Tasks.Task<(global::app.module.ICodeGenerated?, global::app.error.IError?)> Resolve(
                    global::app.goal.steps.step.actions.action.@this action, global::app.actor.context.@this context)
                {
                    var app = context.App!;
                    var __step = action?.Step;
                    var __callFrames = context.CallStack?.Current?.SnapshotChain() ?? (System.Collections.Generic.IReadOnlyList<global::app.callstack.call.@this>)System.Array.Empty<global::app.callstack.call.@this>();

            """);

        // [IsNotNull] validation
        if (info.HasAnyIsNotNull)
        {
            sb.AppendLine("        if (action?.Parameters != null)");
            sb.AppendLine("        {");
            foreach (var name in info.IsNotNullProperties)
            {
                var lower = name.ToLowerInvariant();
                sb.Append($$"""
                                if ((action?.Parameters.FirstOrDefault(d => string.Equals(d.Name, "{{lower}}", StringComparison.OrdinalIgnoreCase))?.Peek().IsNull) ?? true)
                                    return (null, new global::app.error.ServiceError(
                                        "'{{lower}}' must have a value", __step, __callFrames, "ValueRequired", 400));

                    """);
            }
            sb.AppendLine("        }");
        }

        // Missing-required-parameter validation for name slots (Data<variable>, non-nullable).
        var nameProps = info.Properties
            .OfType<DataProperty>()
            .Where(p => p.IsName && !p.IsNullable)
            .ToList();
        if (nameProps.Count > 0)
        {
            sb.AppendLine("        if (action?.Parameters != null)");
            sb.AppendLine("        {");
            foreach (var prop in nameProps)
            {
                var lower = prop.Name.ToLowerInvariant();
                sb.Append($$"""
                                if (action?.Parameters.FirstOrDefault(d => string.Equals(d.Name, "{{lower}}", StringComparison.OrdinalIgnoreCase))?.Peek() == null)
                                    return (null, new global::app.error.ServiceError(
                                        "Required parameter '{{lower}}' is missing or null", __step, __callFrames, "MissingRequiredParameter", 400));

                    """);
            }
            sb.AppendLine("        }");
        }

        // Resolve each parameter into a local (decode %var%/literal in this context).
        // Setting key per param is module.action.param, read off the tree location: module = first
        // segment after "app.module.", action = the record/class name (== the action name).
        const string settingModulePrefix = "app.module.";
        var settingModule = info.Namespace.StartsWith(settingModulePrefix)
            ? info.Namespace.Substring(settingModulePrefix.Length).Split('.')[0]
            : info.Namespace;
        var settingAction = info.ClassName;
        var dataProps = info.Properties.OfType<DataProperty>().ToList();
        foreach (var prop in dataProps)
            prop.EmitResolveLocal(sb, settingModule, settingAction);

        sb.AppendLine();

        // Construct the fresh instance, binding resolved params via the object initializer.
        if (dataProps.Count == 0)
        {
            sb.AppendLine($"        var __instance = new {info.ClassName}(context);");
        }
        else
        {
            sb.AppendLine($"        var __instance = new {info.ClassName}(context)");
            sb.AppendLine("        {");
            for (int i = 0; i < dataProps.Count; i++)
            {
                var comma = i < dataProps.Count - 1 ? "," : "";
                sb.AppendLine($"            {dataProps[i].InitAssignment}{comma}");
            }
            sb.AppendLine("        };");
        }

        sb.Append("""

                    var __err = await __instance.Attach(action, context);
                    if (__err != null) return (null, __err);
                    return (__instance, null);
                }

            """);
    }

    private static void EmitAttach(StringBuilder sb, ActionClassInfo info)
    {
        sb.Append("""
                public async System.Threading.Tasks.Task<global::app.error.IError?> Attach(
                    global::app.goal.steps.step.actions.action.@this? action, global::app.actor.context.@this context)
                {
                    var app = context.App!;
                    __action = action;
                    var __step = action?.Step;
                    var __callFrames = context.CallStack?.Current?.SnapshotChain() ?? (System.Collections.Generic.IReadOnlyList<global::app.callstack.call.@this>)System.Array.Empty<global::app.callstack.call.@this>();

            """);

        if (info.ImplementsIAction) sb.AppendLine("        Action = action!;");
        if (info.ImplementsIStep) sb.AppendLine("        Step = action?.Step!;");
        if (info.ImplementsIStatic)
        {
            const string prefix = "app.module.";
            var moduleName = info.Namespace.StartsWith(prefix)
                ? info.Namespace.Substring(prefix.Length).Split('.')[0]
                : info.Namespace;
            sb.AppendLine($"        Static = context.GetModuleStatic(\"{moduleName}\");");
        }
        if (info.ImplementsIChannel)
        {
            sb.Append("""
                        {
                            // The channel param rides as a text value after born-native —
                            // its string face is the channel name (a raw `as string` would
                            // null a text.@this and silently default to Output).
                            var __channelName = action?.Parameters?.FirstOrDefault(d => string.Equals(d.Name, "channel", System.StringComparison.OrdinalIgnoreCase))?.Peek()?.ToString();
                            Channel = (context.Actor ?? app.User).Channel.Resolve(__channelName);
                            if (Channel == null)
                                return new global::app.error.ServiceError(
                                    $"Channel '{__channelName ?? "output"}' not found", __step, __callFrames, "ChannelNotFound", 404);
                        }

                """);
        }

        // [Code] providers
        foreach (var prop in info.Properties.OfType<CodeProperty>())
            prop.EmitAttach(sb);

        // IEvent surface — reads the (now-populated) param props.
        foreach (var name in info.IEventPropertyNames)
        {
            sb.Append($$"""
                        if ({{name}}?.Event != null)
                            context.Event = {{name}}.Event;

                """);
        }

        sb.Append("""
                    await System.Threading.Tasks.Task.CompletedTask;
                    return null;
                }

            """);
    }

    private static void EmitExecute(StringBuilder sb)
    {
        sb.Append("""
                public async System.Threading.Tasks.Task<global::app.data.@this> Execute()
                {
                    try { return await Run(); }
                    catch (System.Exception ex) when (ex is not (System.OperationCanceledException or System.OutOfMemoryException or System.StackOverflowException))
                    {
                        // Bare exceptions from Run() (NRE, InvalidCast, etc.) reach the user
                        // as "Object reference not set" with no module.action context. Wrap
                        // here so the message tells the reader which action's Run() threw.
                        var __mod = __action?.Module ?? "?";
                        var __act = __action?.ActionName ?? "?";
                        var __step = __action?.Step;
                        var __callFrames = Context?.CallStack?.Current?.SnapshotChain() ?? (System.Collections.Generic.IReadOnlyList<global::app.callstack.call.@this>)System.Array.Empty<global::app.callstack.call.@this>();
                        // A typed AppException carries a domain Key (VariableNotFound, …) — preserve
                        // it; a bare exception falls back to its type name.
                        var __ap = ex as global::app.error.AppException;
                        return global::app.data.@this.FromError(new global::app.error.ServiceError(
                            $"{__mod}.{__act}: {ex.GetType().Name}: {ex.Message}",
                            __step!, __callFrames, __ap?.Key ?? ex.GetType().Name, __ap?.StatusCode ?? 500)
                        { Exception = ex });
                    }
                }

            """);
    }

    private static void EmitHelpers(StringBuilder sb)
    {
        sb.Append("""
                private static global::app.data.@this __ResolveData(
                    global::app.goal.steps.step.actions.action.@this? action, string name, global::app.actor.context.@this context)
                {
                    var data = action?.GetParameter(name, context);
                    if (data == null) return global::app.data.@this.NotFound(name);
                    data.Context = context;
                    return data;
                }

                // Wraps a resolution error with the action's module.action context so the
                // reader can locate the failing call site. The raw error from Data<T>.As<T>
                // only carries source/target type names — useless without the action name.
                private static global::app.error.IError __PrefixActionContext(
                    global::app.error.IError err, global::app.goal.steps.step.actions.action.@this? action)
                {
                    if (action == null) return err;
                    var msg = $"{action.Module}.{action.ActionName}: {err.Message}";
                    return new global::app.error.ActionError(msg, err.Key ?? "ActionError", err.StatusCode);
                }

            """);
    }

    private static void EmitSnapshotPublic(StringBuilder sb)
    {
        // Public surface for the call-stack catch path.
        sb.Append("""
                public System.Collections.Generic.List<global::app.error.ParamSnapshot> SnapshotParams()
                    => __SnapshotParams();

            """);
    }

    private static void EmitSnapshotInternal(StringBuilder sb, ActionClassInfo info)
    {
        sb.Append("""
                private System.Collections.Generic.List<global::app.error.ParamSnapshot> __SnapshotParams()
                {
                    var __list = new System.Collections.Generic.List<global::app.error.ParamSnapshot>();
            """);
        sb.AppendLine();
        foreach (var prop in info.Properties)
            prop.EmitSnapshotEntry(sb);
        sb.Append("""
                    return __list;
                }
            """);
        sb.AppendLine();
    }
}
