using System.Linq;
using System.Text;
using PLang.Generators.Discovery;
using PLang.Generators.Emission.Property;
using DataProperty = PLang.Generators.Emission.Property.Data.@this;
using CodeProperty = PLang.Generators.Emission.Property.Code.@this;

namespace PLang.Generators.Emission.Action;

/// <summary>
/// Per-handler emission. Builds the partial-class shell, marker auto-provisions,
/// per-property bodies (delegated to ActionProperty.EmitProperty), the thin
/// ExecuteAsync, and the __SnapshotParams body (delegated to
/// ActionProperty.EmitSnapshotEntry).
///
/// Emission uses C# raw string literals (`$$"""..."""`). With `$$`, single `{` `}`
/// are literal and `{{name}}` is interpolation, so the emitted shape reads top-to-
/// bottom as it would appear in the generated .g.cs file. The closing `"""` column
/// determines how much leading whitespace is stripped from each line.
/// </summary>
public static class @this
{
    public static string Emit(ActionClassInfo info)
    {
        var sb = new StringBuilder();

        sb.Append($$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Linq;
            using System.Text.RegularExpressions;

            namespace {{info.Namespace}};

            partial class {{info.ClassName}} : global::app.modules.ICodeGenerated, global::app.modules.IClass
            {

            """);

        EmitMarkers(sb, info);
        EmitResolutionState(sb);
        EmitProperties(sb, info);
        EmitDataAndErrorHelpers(sb, info);
        EmitExecuteAsync(sb, info);
        EmitSnapshotPublic(sb);
        EmitLegacyHelpers(sb);
        EmitSnapshotInternal(sb, info);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitMarkers(StringBuilder sb, ActionClassInfo info)
    {
        if (info.ImplementsIContext)
            sb.Append("""
                    public global::app.actor.context.@this Context { get; set; } = null!;

                """);
        if (info.ImplementsIChannel)
            sb.Append("""
                    public global::app.channels.channel.@this Channel { get; set; } = null!;

                """);
        if (info.ImplementsIAction)
            sb.Append("""
                    public global::app.goals.goal.steps.step.actions.action.@this Action { get; set; } = null!;

                """);
        if (info.ImplementsIStep)
            sb.Append("""
                    public global::app.goals.goal.steps.step.@this Step { get; set; } = null!;

                """);
        if (info.ImplementsIStatic)
            sb.Append("""
                    public System.Collections.Concurrent.ConcurrentDictionary<string, object?> Static { get; set; } = null!;

                """);
    }

    private static void EmitResolutionState(StringBuilder sb)
    {
        sb.Append("""
                private global::app.goals.goal.steps.step.actions.action.@this? __action;
                private global::app.@this? __app;
                private global::app.data.@this? __resolutionError;

            """);
    }

    private static void EmitProperties(StringBuilder sb, ActionClassInfo info)
    {
        foreach (var prop in info.Properties)
            prop.EmitProperty(sb);
    }

    private static void EmitDataAndErrorHelpers(StringBuilder sb, ActionClassInfo info)
    {
        var hasDataProp = info.Properties.Any(p => p.Name == "Data");
        if (!hasDataProp)
        {
            sb.Append("""
                    protected static global::app.data.@this Data() => global::app.data.@this.Ok();
                    protected static global::app.data.@this Data(object? value) => global::app.data.@this.Ok(value);
                    protected static global::app.data.@this Data(object? value, global::app.data.type? type) => global::app.data.@this.Ok(value, type);

                """);
        }
        var hasErrorProp = info.Properties.Any(p => p.Name == "Error");
        if (!hasErrorProp)
        {
            sb.Append("""
                    protected static global::app.data.@this Error(global::app.errors.IError error) => global::app.data.@this.FromError(error);

                """);
        }
        sb.AppendLine();
    }

    private static void EmitExecuteAsync(StringBuilder sb, ActionClassInfo info)
    {
        sb.Append("""
                public async System.Threading.Tasks.Task<global::app.data.@this> ExecuteAsync(
                    global::app.goals.goal.steps.step.actions.action.@this action, global::app.actor.context.@this context)
                {
                    __action = action;
                    __app = context.App;
                    var app = __app!;
                    __resolutionError = null;
                    if (action != null)
                    {

            """);

        // Reset backing fields per call so reused handler instances re-derive.
        // Skip when action is null (direct C# composition via init keeps init values).
        foreach (var prop in info.Properties)
        {
            if (prop is CodeProperty) continue;
            sb.Append($$"""
                                __{{prop.Name}}_backing = default;
                                __{{prop.Name}}_set = false;

                    """);
        }

        sb.Append("""
                    }
                    var __step = __action?.Step;
                    var __callFrames = context.CallStack?.Current?.SnapshotChain() ?? (System.Collections.Generic.IReadOnlyList<global::app.callstack.call.@this>)System.Array.Empty<global::app.callstack.call.@this>();

            """);

        if (info.ImplementsIContext) sb.AppendLine("        Context = context;");
        if (info.ImplementsIChannel)
        {
            sb.Append("""
                        {
                            var __channelName = __action?.Parameters?.FirstOrDefault(d => string.Equals(d.Name, "channel", System.StringComparison.OrdinalIgnoreCase))?.Value as string;
                            Channel = (context.Actor ?? app.User).Channels.Resolve(__channelName);
                            if (Channel == null)
                                return global::app.data.@this.FromError(new global::app.errors.ServiceError(
                                    $"Channel '{__channelName ?? "output"}' not found", __step, __callFrames, "ChannelNotFound", 404));
                        }

                """);
        }
        if (info.ImplementsIAction) sb.AppendLine("        Action = __action!;");
        if (info.ImplementsIStep) sb.AppendLine("        Step = __action?.Step!;");
        if (info.ImplementsIStatic)
        {
            const string prefix = "app.modules.";
            var moduleName = info.Namespace.StartsWith(prefix)
                ? info.Namespace.Substring(prefix.Length).Split('.')[0]
                : info.Namespace;
            sb.AppendLine($"        Static = context.GetModuleStatic(\"{moduleName}\");");
        }

        // Eager [Code] resolution
        foreach (var prop in info.Properties.OfType<CodeProperty>())
        {
            sb.Append($$"""
                        var __{{prop.Name}}_result = app.Code.Get<{{prop.TypeName}}>();
                        if (!__{{prop.Name}}_result.Success) return __{{prop.Name}}_result;
                        __{{prop.Name}}_backing = __{{prop.Name}}_result.Value!;

                """);
        }
        sb.AppendLine();

        // IEvent surface
        foreach (var name in info.IEventPropertyNames)
        {
            sb.Append($$"""
                        if ({{name}}?.Event != null)
                            context.Event = {{name}}.Event;

                """);
        }

        // [IsNotNull] validation
        if (info.HasAnyIsNotNull)
        {
            sb.AppendLine("        if (__action?.Parameters != null)");
            sb.AppendLine("        {");
            foreach (var name in info.IsNotNullProperties)
            {
                var lower = name.ToLowerInvariant();
                sb.Append($$"""
                                if (__action?.Parameters.FirstOrDefault(d => string.Equals(d.Name, "{{lower}}", StringComparison.OrdinalIgnoreCase))?.Value == null)
                                    return global::app.data.@this.FromError(new global::app.errors.ServiceError(
                                        "'{{lower}}' must have a value", __step, __callFrames, "ValueRequired", 400));

                    """);
            }
            sb.AppendLine("        }");
        }

        // Missing-required-parameter validation for IRawNameResolvable slots.
        // Restores pre-v7 RawScalarValidations contract — missing or null variable-name
        // parameter surfaces a MissingRequiredParameter ServiceError before Run() is
        // invoked, instead of bubbling up as an NRE through the implicit Variable→string
        // operator. Auditor v2 finding #1.
        var rawNameProps = info.Properties
            .OfType<DataProperty>()
            .Where(p => p.IsRawNameResolvable && !p.IsNullable)
            .ToList();
        if (rawNameProps.Count > 0)
        {
            sb.AppendLine("        if (__action?.Parameters != null)");
            sb.AppendLine("        {");
            foreach (var prop in rawNameProps)
            {
                // Mirror IsNotNull's serialization convention: lowercase the property name
                // for the parameter-list match, which is how .pr emits parameter keys.
                var lower = prop.Name.ToLowerInvariant();
                sb.Append($$"""
                                if (__action?.Parameters.FirstOrDefault(d => string.Equals(d.Name, "{{lower}}", StringComparison.OrdinalIgnoreCase))?.Value == null)
                                    return global::app.data.@this.FromError(new global::app.errors.ServiceError(
                                        "Required parameter '{{lower}}' is missing or null", __step, __callFrames, "MissingRequiredParameter", 400));

                    """);
            }
            sb.AppendLine("        }");
        }

        sb.Append("""
                    if (__resolutionError != null) return __PrefixActionContext(__resolutionError);

                    global::app.data.@this __runResult;
                    try { __runResult = await Run(); }
                    catch (System.Exception ex) when (ex is not (System.OperationCanceledException or System.OutOfMemoryException or System.StackOverflowException))
                    {
                        // Bare exceptions from Run() (NRE, InvalidCast, etc.) reach the user
                        // as "Object reference not set" with no module.action context. Wrap
                        // here so the message tells the reader which action's Run() threw.
                        // Original exception preserved on the ServiceError.Exception so the
                        // C# stack stays available for diagnostic display.
                        var mod = __action?.Module ?? "?";
                        var act = __action?.ActionName ?? "?";
                        return global::app.data.@this.FromError(new global::app.errors.ServiceError(
                            $"{mod}.{act}: {ex.GetType().Name}: {ex.Message}",
                            __step!, __callFrames, ex.GetType().Name, 500)
                        { Exception = ex });
                    }
                    // Data<T> getters fire DURING Run() — they capture cycle/depth-trip into
                    // __resolutionError as the property is touched. Surface it now so a Run()
                    // that read .Value of a FromError-Data and produced a default-shaped result
                    // doesn't bury the resolution failure.
                    if (__resolutionError != null) return __PrefixActionContext(__resolutionError);
                    return __runResult;
                }

                // Wraps the resolution error with the action's module.action context so the
                // reader can locate the failing call site without reading the call stack. The
                // raw error from Data<T>.As<T> only carries source/target type names — useless
                // without knowing which action and parameter the conversion was for.
                private global::app.data.@this __PrefixActionContext(global::app.data.@this err)
                {
                    if (__action == null || err.Error == null) return err;
                    var orig = err.Error;
                    var msg = $"{__action.Module}.{__action.ActionName}: {orig.Message}";
                    return global::app.data.@this.FromError(new global::app.errors.ActionError(msg, orig.Key ?? "ActionError", orig.StatusCode));
                }

            """);
    }

    private static void EmitSnapshotPublic(StringBuilder sb)
    {
        // Public surface for App.Run's catch path.
        sb.Append("""
                public System.Collections.Generic.List<global::app.errors.ParamSnapshot> SnapshotParams()
                    => __SnapshotParams();

            """);
    }

    private static void EmitLegacyHelpers(StringBuilder sb)
    {
        // After v5: only __ResolveData remains. Legacy scalar/[VariableName] emission
        // (which used __Resolve<T>, __HasParam, __StripPercent) is gone — Variable-name
        // slots are Data<Variable> and route through the Data emitter's __ResolveData.
        sb.Append("""
                private global::app.data.@this __ResolveData(string name)
                {
                    var data = __action?.GetParameter(name, Context!);
                    if (data == null) return global::app.data.@this.NotFound(name);
                    data.Context = Context;
                    return data;
                }

            """);
    }

    private static void EmitSnapshotInternal(StringBuilder sb, ActionClassInfo info)
    {
        sb.Append("""
                private System.Collections.Generic.List<global::app.errors.ParamSnapshot> __SnapshotParams()
                {
                    var __list = new System.Collections.Generic.List<global::app.errors.ParamSnapshot>();
            """);
        sb.AppendLine();
        foreach (var prop in info.Properties)
            prop.EmitSnapshotEntry(sb);
        sb.Append("""
                    return __list;
                }
            """);
        sb.AppendLine();
    }
}
