name: Build macOS Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build PlangConsole/PLangConsole.csproj --configuration Release

    - name: Publish for macOS
      run: dotnet publish PlangConsole/PLangConsole.csproj -c Release -r osx-x64 --self-contained

    - name: Create installer directory
      run: |
        mkdir -p ./package/Applications/Plang
        cp -R ./bin/Release/net8.0/osx-x64/publish/* ./package/Applications/Plang

    - name: Create macOS .pkg installer
      run: |
        pkgbuild --root ./package --identifier is.plang --version 0.1.15.2 --install-location /Applications/Plang PlangInstaller.pkg
    
    - name: Sign the .pkg file
      run: |
        codesign --sign "Developer ID Installer: Ingi Gauti" PlangInstaller.pkg

    - name: Notarize the .pkg
      run: |
        xcrun altool --notarize-app -f PlangInstaller.pkg --primary-bundle-id is.plang --username "$APPLE_ID" --password "$APP_SPECIFIC_PASSWORD"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: PlangInstaller.pkg
        path: PlangInstaller.pkg
