using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PLang.Generators;

[Generator]
public class LazyParamsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all partial classes that inherit BaseClass<T>
        var handlerDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsPartialClassWithBaseClassT(node),
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static info => info is not null);

        context.RegisterSourceOutput(handlerDeclarations, static (spc, info) =>
        {
            if (info is null) return;
            var source = GenerateCode(info);
            spc.AddSource($"{info.HandlerFullName}.g.cs", source);
        });
    }

    private static bool IsPartialClassWithBaseClassT(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax classDecl) return false;
        if (!classDecl.Modifiers.Any(SyntaxKind.PartialKeyword)) return false;
        if (classDecl.BaseList is null) return false;

        // Check if any base type looks like BaseClass<Something>
        foreach (var baseType in classDecl.BaseList.Types)
        {
            if (baseType.Type is GenericNameSyntax generic &&
                generic.Identifier.Text == "BaseClass" &&
                generic.TypeArgumentList.Arguments.Count == 1)
            {
                return true;
            }
        }
        return false;
    }

    private static HandlerInfo? GetHandlerInfo(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var classSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl);
        if (classSymbol is null) return null;

        // Find the BaseClass<T> base type
        var baseType = classSymbol.BaseType;
        while (baseType is not null)
        {
            if (baseType.Name == "BaseClass" && baseType.TypeArguments.Length == 1)
            {
                var paramType = baseType.TypeArguments[0] as INamedTypeSymbol;
                if (paramType is null) return null;

                // Get the virtual properties from the param record
                // Skip compiler-generated properties like EqualityContract
                var properties = new List<PropertyInfo>();
                foreach (var member in paramType.GetMembers())
                {
                    if (member is IPropertySymbol prop && prop.IsVirtual && !prop.IsStatic
                        && prop.DeclaredAccessibility == Accessibility.Public
                        && prop.Name != "EqualityContract")
                    {
                        properties.Add(new PropertyInfo(
                            prop.Name,
                            prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                            prop.NullableAnnotation == NullableAnnotation.Annotated));
                    }
                }

                // Generate for ALL handlers, even 0-property records
                return new HandlerInfo(
                    classSymbol.ContainingNamespace.ToDisplayString(),
                    classSymbol.Name,
                    $"{classSymbol.ContainingNamespace}.{classSymbol.Name}",
                    paramType.Name,
                    paramType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    properties);
            }
            baseType = baseType.BaseType;
        }

        return null;
    }

    private static string GenerateCode(HandlerInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text.RegularExpressions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();

        if (info.Properties.Count > 0)
        {
            // Generate the lazy record for handlers with properties
            var generatedRecordName = $"{info.ParamTypeName}__Generated";
            sb.AppendLine($"public sealed record {generatedRecordName} : {info.ParamTypeFullName}");
            sb.AppendLine("{");
            sb.AppendLine("    private readonly List<PLang.Runtime2.Memory.Data> _data;");
            sb.AppendLine("    private readonly PLang.Runtime2.Memory.MemoryStack _memory;");
            sb.AppendLine();
            sb.AppendLine($"    public {generatedRecordName}(List<PLang.Runtime2.Memory.Data> data, PLang.Runtime2.Memory.MemoryStack memory)");
            sb.AppendLine("    {");
            sb.AppendLine("        _data = data;");
            sb.AppendLine("        _memory = memory;");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Override each virtual property
            foreach (var prop in info.Properties)
            {
                sb.AppendLine($"    public override {prop.TypeName} {prop.Name} {{ get => Resolve<{prop.TypeName}>(\"{prop.Name}\")!; init {{ }} }}");
            }

            sb.AppendLine();
            sb.AppendLine("    private T? Resolve<T>(string name)");
            sb.AppendLine("    {");
            sb.AppendLine("        var data = FindData(name);");
            sb.AppendLine("        if (data?.Value is string str && str.Contains('%'))");
            sb.AppendLine("        {");
            sb.AppendLine("            var fullMatch = Regex.Match(str, @\"^%([^%]+)%$\");");
            sb.AppendLine("            if (fullMatch.Success)");
            sb.AppendLine("                return (T?)PLang.Runtime2.Utility.TypeMapping.ConvertTo(");
            sb.AppendLine("                    _memory.GetValue(fullMatch.Groups[1].Value), typeof(T));");
            sb.AppendLine("            var interpolated = Regex.Replace(str, @\"%([^%]+)%\",");
            sb.AppendLine("                m => _memory.GetValue(m.Groups[1].Value)?.ToString() ?? \"\");");
            sb.AppendLine("            return (T?)(object)interpolated;");
            sb.AppendLine("        }");
            sb.AppendLine("        return (T?)PLang.Runtime2.Utility.TypeMapping.ConvertTo(data?.Value, typeof(T));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private PLang.Runtime2.Memory.Data? FindData(string name)");
            sb.AppendLine("    {");
            sb.AppendLine("        return _data.FirstOrDefault(d => string.Equals(d.Name, name, StringComparison.OrdinalIgnoreCase));");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Generate partial handler class implementing ICodeGenerated
        sb.AppendLine($"partial class {info.HandlerName} : PLang.Runtime2.Modules.ICodeGenerated");
        sb.AppendLine("{");
        sb.AppendLine("    public System.Threading.Tasks.Task<PLang.Runtime2.Core.Return> CodeGeneratedExecuteAsync(");
        sb.AppendLine("        List<PLang.Runtime2.Memory.Data> parameters, PLang.Runtime2.Core.Engine engine, PLang.Runtime2.Context.PLangContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        Initialize(engine, context);");

        if (info.Properties.Count > 0)
        {
            var generatedRecordName = $"{info.ParamTypeName}__Generated";
            sb.AppendLine($"        var lazy = new {generatedRecordName}(parameters, context.MemoryStack);");
            sb.AppendLine($"        return ExecuteAsync(lazy);");
        }
        else
        {
            // 0-property record: just call ExecuteAsync(null)
            sb.AppendLine($"        return ExecuteAsync(({info.ParamTypeFullName}?)null);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

internal class HandlerInfo
{
    public string Namespace { get; }
    public string HandlerName { get; }
    public string HandlerFullName { get; }
    public string ParamTypeName { get; }
    public string ParamTypeFullName { get; }
    public List<PropertyInfo> Properties { get; }

    public HandlerInfo(string ns, string handlerName, string handlerFullName,
        string paramTypeName, string paramTypeFullName, List<PropertyInfo> properties)
    {
        Namespace = ns;
        HandlerName = handlerName;
        HandlerFullName = handlerFullName;
        ParamTypeName = paramTypeName;
        ParamTypeFullName = paramTypeFullName;
        Properties = properties;
    }
}

internal class PropertyInfo
{
    public string Name { get; }
    public string TypeName { get; }
    public bool IsNullable { get; }

    public PropertyInfo(string name, string typeName, bool isNullable)
    {
        Name = name;
        TypeName = typeName;
        IsNullable = isNullable;
    }
}
